#pragma once

typedef enum _AGAINSTRESULT
{
	AGAINST_SUCCESS,

	// Vulkan
	AGAINST_ERROR_GRAPHICS_POPULATE_INSTANCE_LAYERS_AND_EXTENSIONS,
	AGAINST_ERROR_GRAPHICS_CREATE_INSTANCE,
	AGAINST_ERROR_GRAPHICS_SETUP_DEBUG_UTILS_MESSENGER,
	AGAINST_ERROR_GRAPHICS_CREATE_DEBUG_UTILS_MESSENGER,
	AGAINST_ERROR_GRAPHICS_DESTROY_DEBUG_UTILS_MESSENGER,
	AGAINST_ERROR_GRAPHICS_CREATE_SURFACE,
	AGAINST_ERROR_GRAPHICS_GET_PHYSICAL_DEVICE,
	AGAINST_ERROR_GRAPHICS_POPULATE_DEVICE_LAYERS_AND_EXTENSIONS,
	AGAINST_ERROR_GRAPHICS_CREATE_GRAPHICS_DEVICE,
	AGAINST_ERROR_GRAPHICS_SURFACE_SUPPORT,
	AGAINST_ERROR_GRAPHICS_CREATE_SWAPCHAIN,
	AGAINST_ERROR_GRAPHICS_CREATE_IMAGE_VIEW,
	AGAINST_ERROR_GRAPHICS_CREATE_BUFFER,
	AGAINST_ERROR_GRAPHICS_ALLOCATE_MEMORY,
	AGAINST_ERROR_GRAPHICS_BIND_BUFFER_MEMORY,
	AGAINST_ERROR_GRAPHICS_CREATE_IMAGE,
	AGAINST_ERROR_GRAPHICS_BIND_IMAGE_MEMORY,
	AGAINST_ERROR_GRAPHICS_MAP_MEMORY,
	AGAINST_ERROR_GRAPHICS_CREATE_DESCRIPTOR_SET_LAYOUT,
	AGAINST_ERROR_GRAPHICS_CREATE_PIPELINE_LAYOUT,
	AGAINST_ERROR_GRAPHICS_CREATE_DESCRIPTOR_POOL,
	AGAINST_ERROR_GRAPHICS_ALLOCATE_DESCRIPTOR_SET,
	AGAINST_ERROR_GRAPHICS_CREATE_RENDER_PASS,
	AGAINST_ERROR_GRAPHICS_CREATE_SHADER_MODULE,
	AGAINST_ERROR_GRAPHICS_CREATE_FRAMEBUFFER,
	AGAINST_ERROR_GRAPHICS_BEGIN_COMMAND_BUFFER,
	AGAINST_ERROR_GRAPHICS_END_COMMAND_BUFFER,
	AGAINST_ERROR_GRAPHICS_RESET_COMMAND_BUFFER,
	AGAINST_ERROR_GRAPHICS_CREATE_COMMAND_POOL,
	AGAINST_ERROR_GRAPHICS_ALLOCATE_COMMAND_BUFFER,
	AGAINST_ERROR_GRAPHICS_CREATE_GRAPHICS_PIPELINE,
	AGAINST_ERROR_GRAPHICS_CREATE_SEMAPHORE,
	AGAINST_ERROR_GRAPHICS_ACQUIRE_NEXT_IMAGE,
	AGAINST_ERROR_GRAPHICS_WAIT_FOR_FENCES,
	AGAINST_ERROR_GRAPHICS_CREATE_FENCE,
	AGAINST_ERROR_GRAPHICS_RESET_FENCE,
	AGAINST_ERROR_GRAPHICS_QUEUE_SUBMIT,
	AGAINST_ERROR_GRAPHICS_QUEUE_PRESENT,
	AGAINST_ERROR_GRAPHICS_UPDATE_UNIFORM_BUFFER,
	AGAINST_ERROR_GRAPHICS_CREATE_SAMPLER,

	// GLTF
	AGAINST_ERROR_GLTF_IMPORT,

	// Network

	// Physics

	// System
	AGAINST_ERROR_SYSTEM_ALLOCATE_MEMORY,
	AGAINST_ERROR_SYSTEM_TMP_FILE

} AGAINST_RESULT;
